# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install FrontEnd
      run: npm install
      working-directory: FrontEnd
    - name: BuildFront
      run: npm run-script build
      working-directory: FrontEnd
    - name: build OHIF
      run: |
        mkdir ohif
        cd ohif
        git clone https://github.com/OHIF/Viewers.git
        cd Viewers
        yarn install
        QUICK_BUILD=true PUBLIC_URL=/viewer-ohif/ yarn run build
      working-directory: FrontEnd
    - name: copy FrontEnd build to BackEnd
      run : mv build ../BackEnd
      working-directory: FrontEnd
    - name : copy OHIF
      run : |
        rm ./ohif/Viewers/platform/viewer/dist/app-config.js
        cp ./ohif/Viewers/platform/viewer/dist/ ../BackEnd/build/viewer-ohif/
      working-directory: FrontEnd
    - name: copy Stone Of Orthanc
      run: |
        mkdir stone
        cd stone
        wget https://lsb.orthanc-server.com/stone-webviewer/1.0/wasm-binaries.zip
        unzip wasm-binaries.zip -d .
        rm wasm-binaries.zip
        rm./wasm-binaries/StoneWebViewer/configuration.json
        cp ../../BackEnd/build/viewer-stone/configuration.json  ./wasm-binaries/StoneWebViewer
        cp ./wasm-binaries/StoneWebViewer/ ../../BackEnd/build/viewer-stone/
      working-directory: FrontEnd
    - name: create ZIP distribution
      run : zip -r OrthancToolsJS.zip .
      working-directory: BackEnd
    - name: Create Release
      if: github.event.pull_request.merged == true
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.pull_request.title }}
        release_name: Release ${{ github.event.pull_request.title }}
        draft: true
        prerelease: true
    - name: Upload Release Asset
      if: github.event.pull_request.merged == true
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./BackEnd/OrthancToolsJS.zip
        asset_name: OrthancToolsJS.zip
        asset_content_type: application/zip
    - uses: actions/upload-artifact@v1
      with:
        name: OrthancToolsJS
        path: ./BackEnd/OrthancToolsJS.zip
    - name: Install dependencies
      run: npm install
      working-directory: BackEnd
    - name: Test BackEnd
      run: npm test
      working-directory: BackEnd
      env:
        CI: true

